name: Run Gradle
on:
  push:
    branches: [ before-lab3 ]
  pull_request:
    branches: [ before-lab3 ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      if: runner.os == 'Linux'
      run: chmod +x BasicBots/gradlew
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build --scan
        build-root-directory: BasicBots
        wrapper-directory: BasicBots
      id: gradle
    - name: "Comment failed build scan url"
      uses: actions/github-script@v3
      if: github.event_name == 'pull_request' && failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
          })  
    - name: "Comment successful build scan url"
      uses: actions/github-script@v3
      if: github.event_name == 'pull_request' && success()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ github.workflow }} succeeded: ${{ steps.gradle.outputs.build-scan-url }}'
          })  
